imageLoader.ts, next.config.ts
Added a custom image loader in `next.config.ts` to optimize image delivery through Cloudflare's CDN. Introduced `imageLoader.ts` to handle image transformation parameters such as width and quality. This ensures better performance in production while maintaining original behavior during development.
=> Set up custom image loader for Cloudflare

src/app/layout.tsx, src/app/page.tsx
This pull request includes several updates to the `RootLayout` and `Home` components to enhance the mobile and desktop user experience and update some text content.
* Added a mobile header with a two-line structure, including a logo, title, hamburger menu, and social links. [[1]](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3R27-R31) [[2]](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3L44-R132)
* Introduced a mobile menu that can be toggled with a checkbox input, providing links to the blog, events, and about pages.
* Updated the desktop header to include a more structured layout with links and social media icons.
* Updated the tagline in the footer to "Onde o código é nossa arte e a tecnologia é nossa paixão."
* …
=> Adjust header nav for mobile navigation

src/app/about/page.tsx, src/app/events/page.tsx, src/app/layout.tsx, src/app/page.tsx, src/app/topics/[topic]/page.tsx
- Fix discord links
- Fix featured content link and order
#3 #4 #7 #2
=> Adjust and fix featured topics on home and discord links

src/app/about/page.tsx, src/app/not-found.tsx, src/app/topics/[topic]/page.tsx
This pull request includes several updates to the visual layout and filtering logic of different pages in the application. The most important changes include modifying the margin and background settings of various components and updating the filtering logic for posts by topic.
Visual layout updates:
* [`src/app/about/page.tsx`](diffhunk://#diff-d38aaae18142756b8b93ec0043df16888550dfded455e182cc0e4a81eb8286e2L3-R3): Adjusted the margin and background settings of the main container to improve spacing and removed the "Contato" section. [[1]](diffhunk://#diff-d38aaae18142756b8b93ec0043df16888550dfded455e182cc0e4a81eb8286e2L3-R3) [[2]](diffhunk://#diff-d38aaae18142756b8b93ec0043df16888550dfded455e182cc0e4a81eb8286e2L50-L62)
* [`src/app/not-found.tsx`](diffhunk://#diff-f656f59519a290bb5f099f48ce …
=> Fix Topic list logic

src/app/about/page.tsx
- Updated the description to emphasize software engineering and best practices.
- Expanded the mission statement to include community growth and support.
- Enhanced the "What We Do" section with specific topics and activities, including algorithms, system design, and advanced topics discussions.
- Improved overall messaging to better reflect the community's goals and offerings.
=> Revise AboutPage content for clarity and inclusivity

src/app/layout.tsx, src/app/page.tsx, src/app/topics/[topic]/page.tsx
This pull request includes several updates to the `src/app` directory to improve the content and navigation of the Craft & Code Club website. The changes involve updating metadata, modifying navigation links, and correcting typos.
Metadata updates:
* [`src/app/layout.tsx`](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3L12-R13): Updated the title and description to better reflect the focus of the Craft & Code Club community.
Navigation link updates:
* [`src/app/layout.tsx`](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3L180-R186): Reorganized the "Links Rápidos" section to include new topics and changed the order of existing ones.
* [`src/app/layout.tsx`](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc24 …
=> Adjusts footer links and header title/description

README.md
- Transformed the README to introduce the Craft & Code Club blog, detailing community goals and activities.
- Expanded sections on community involvement, technologies used, and instructions for using the template.
- Added guidelines for creating posts in Markdown format and contributing to the project.
- Improved clarity and accessibility of information for new users and contributors.
=> Revise README.md to reflect Craft & Code Club and that it is also a template for other communities to use

src/app/layout.tsx
This pull request includes a change to the `src/app/layout.tsx` file to update the metadata title for the application.
* [`src/app/layout.tsx`](diffhunk://#diff-29d0a55f5ca1a9951042587f8b891bb4cd8b204f5bc855dc2468ed44cde2f5b3L12-R12): Updated the metadata title from "Craft & Code Club - Comunidade de Artesãos de Software" to "Comunidade Craft & Code Club".
=> Update blog title to "Comunidade Craft Code Club"

src/app/about/page.tsx
This pull request includes a small change to the `src/app/about/page.tsx` file. The change corrects and refines the text in the `AboutPage` component to improve clarity and accuracy.
Changes in `AboutPage` component:
* Corrected grammatical errors and improved the phrasing in the description of the community's goals.
=> Corrects and refines the text in the `AboutPage`

_content/posts/ad-click-event-aggregation.md, src/app/posts/[id]/page.tsx
Created a new article about Ad Click Event Aggregation challenges, based on system design discussions. Updated topic tags in the UI to display formatted and capitalized text for better readability.
=> Add new blog post and improve topic display formatting

_content/events/dsa-graphs-dijkstra.md
Adjust the link with a temp link while we upload the actual recording
=> Adjust the link with a temp link while we upload the actual recording (Dijkstra event)

docker-compose.yml, dockerfile, nginx.conf
Created dockerfile and docker compose with nginx to simulate SSG locally
=> ci: Add Dockerfile and Docker Compose to simulate the website locally

_content/events/dsa-graphs-intro-part1.md
=> feat(events): add introductory content for graphs workshop

_content/events/book-ad-click-event-aggregation.md, _content/events/dsa-graphs-dijkstra.md
update registration links for book ad click event and DS…A graphs Dijkstra event
=> fix(events): update registration event links

_content/events/dsa-graphs-dsa-dfs.md
=> feat: add event details for DFS and BFS in graph theory

_content/events/dsa-heapsort.md
=> feat: add event details for Heap Sort algorithm

.github/workflows/codeql-analysis.yml
=> ci: add CodeQL analysis workflow for code scanning

_content/events/dsa-mergesort.md
=> feat: add event details for Merge Sort algorithm

_content/events/dsa-n-ary-tree.md
Added "N-Ary Tree" event for session -> https://www.youtube.com/watch?v=FLZxMQFTqvY&list=PLl10TyPY67Jgbh4QdRlRKr-7PjB9i5hWg
=> feat(events): add event details for N-Ary Tree

_content/events/dsa-binary-heap.md
Added "Binary Heap" event for session -> https://www.youtube.com/watch?v=HVWw20nOLHk&list=PLl10TyPY67Jgbh4QdRlRKr-7PjB9i5hWg
=> feat(events): add "Binary Heap" event

.github/workflows/cloudflare-pages-deploy.yml
=> Adds Cloudflare Pages Deploy

.github/workflows/cloudflare-pages-deploy.yml
- Adds checkout to the deployment step
=> pipelines: Adds checkout to the deployment step

.github/workflows/cloudflare-pages-deploy.yml
=> ci: Added action to comment on PR

.github/workflows/cloudflare-pages-deploy.yml
- Add branch name to wranger deploy command
=> pipelines: Add branch name to wranger deploy command

_content/events/dsa-graphs-intro-part2.md
=> fix: Event title of Introducão a Grafos - Parte 2

LICENSE
This pull request includes the addition of a new license file to the project. The most important change is the inclusion of the MIT License to the `LICENSE` file.
Licensing:
* [`LICENSE`](diffhunk://#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7R1-R21): Added the MIT License, granting permission to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software under specified conditions.
=> docs: Added license file

package-lock.json, package.json, src/assets/code-stackoverflow-dark.css, src/lib/posts.ts
This PR aims to fix the #25 
Adding code snippets highlights
#25
=> Adding code snippets highlights

src/app/blog/page.tsx, src/app/events/page.tsx, src/app/page.tsx, src/app/posts/[id]/page.tsx, src/app/topics/[topic]/page.tsx
This pull request includes changes to multiple files to standardize the date format displayed across the application. The changes involve converting the date strings to a more readable format using `toLocaleDateString()`.
#19
=> Improve date formatting across multiple pages, using local format

src/app/blog/page.tsx, src/app/events/page.tsx, src/app/page.tsx, src/app/posts/[id]/page.tsx, src/app/topics/[topic]/page.tsx
The first change was using the host local time, but the host is the backend, so the date format is still US format... Changing to be pt-BR standard, we can iterate on that in the near future.
#19 
#19
=> Update date formatting to use 'pt-BR' locale

_content/events/dsa-graphs-bellman-ford.md
=> fix: correct url zoom link for bellman ford meet

_content/events/dsa-graphs-bellman-ford.md
=> fix: use double quotes

_content/posts/dsa-bellman-ford.md
This pull request includes a small change to the `authors` section of the `_content/posts/dsa-bellman-ford.md` file. The change adds a new author to the list.
* Added 'Giovanny Massuia' as an author with the link to their GitHub profile.
=> docs: add author Giovanny Massuia to Bellman-Ford post

_content/events/book-distributed-email-system.md, _content/events/book-storage-system-design.md, docker-compose.yml, package-lock.json
This pull request includes updates to event dates and a change to the Docker Compose configuration for the `c3-website` container. 
Event date updates:
* [`_content/events/book-distributed-email-system.md`](diffhunk://#diff-bea31aa28f91757ca39cd7c1fe172a9fde61055fc7b35efaaddfed570aad84abL4-R4): Updated the event date for the "Clube do Livro: Serviço de Email Distribuído - System Design" event from "2025-02-10" to "2025-02-24".
* [`_content/events/book-storage-system-design.md`](diffhunk://#diff-5bce593cdebb35fb7f1c1161f344c673cb419ba4da5513c0503b2419e0d89285L4-R4): Updated the event date for the "Clube do Livro: Armazenamento de Objetos Estilo S3 - System Design" event from "2025-02-24" to "2025-03-03".
Docker Compose configuration change:
* …
=> fix: adjust event dates

_content/events/dsa-floyd-warshall.md
This pull request includes the addition of a new event file for the Floyd Warshall algorithm. The most important change is the creation of a new event entry in the `_content/events` directory.
Event addition:
* [`_content/events/dsa-floyd-warshall.md`](diffhunk://#diff-ab349453fdd293a67a2662ec1599f094690b715932c514a9facc16cea167e59dR1-R9): Added a new event titled "Floyd Warshall" with a description, date, time, location, type, and registration link.
=> feat: add event details for Floyd Warshall algorithm session

_content/events/dsa-topological-sorting.md
This pull request includes a new event page for "Topological Sorting" in the `_content/events` directory. The page provides details about the event, including the title, description, date, time, location, type, and registration link.
Event details added:
* [`_content/events/dsa-topological-sorting.md`](diffhunk://#diff-9c3b99895799436853e8bd3d6ca59d6dbd5d56f49149233b313873c2ffe88b21R1-R9): Created a new event page for "Topological Sorting" with relevant information such as title, description, date, time, location, type, and registration link.
=> feat: add event page for Topological Sorting algorithm

_content/events/book-realtime-gaming-leaderboard.md
Create the event for "Clube do Livro: Real-time Gaming Leaderboard: Desafios e Soluções"
=> feat: add event details for real-time gaming leaderboard discussion

src/app/events/page.tsx
This pull request includes a minor change to the `EventsPage` function in the `src/app/events/page.tsx` file. The change involves modifying the format of the `dates` parameter in the URL search parameters.
* [`src/app/events/page.tsx`](diffhunk://#diff-ee973f6605140da0b3357cef7c9f9b797e19d625447f4e907b565fbef5e9f76aL35-R35): Updated the `dates` parameter to remove the trailing 'Z' from the ISO string format.
[https://github.com/craft-code-club/blog-c3/issues/120](#120 )
=> [issues/120] fix Google Calendar date format in events page to get local date time

_content/posts/dsa-graph-tips.md
@NelsonBN  @giovannymassuia , penso que pode ser legal ter os tipos ali também, já que na parte das representações falamos muitos nos tipos
=> articles: Adds Graph types section to the Graph Tips Article

.github/workflows/cloudflare-pages-deploy.yml
Fix GitHub Actions, Pull Request comments
=> Fix pipeline comment error

.github/workflows/cloudflare-pages-deploy.yml, src/components/MermaidInitializer.tsx
This PR fixes an issue with Mermaid diagrams not rendering properly during React navigation. Previously, diagrams would only render correctly when accessing a page directly (on full page load), but failed to render when navigating between pages using React Router.
- The solution implements a MermaidInitializer component that:
- Properly initializes Mermaid with consistent configuration
- Detects and processes Mermaid code blocks after navigation events
- Uses pathname changes to trigger re-rendering of diagrams
Cleans up existing diagrams to prevent duplication
This ensures diagrams render correctly in both scenarios: direct page access and client-side navigation.
=> [Fix] Mermaid render on change route

.github/dependabot.yml
=> ci: update dependabot configuration to support multiple Docker manifest locations

.github/workflows/cloudflare-pages-deploy.yml
This new approach will replace the previous command with just the last preview URL when a PR receives new commits.
=> ci: Improve PR comment with the Preview URL

_content/events/book-realtime-gaming-leaderboard.md, _content/events/book-storage-system-design.md
fix(events): update event dates for real-time gaming leaderboard and storage system design
=> fix(events): update event dates for real-time gaming leaderboard and storage system design

_content/posts/dsa-graph-tips.md, package-lock.json
=> fix: update graph representation in dsa-graph-tips.md

_content/posts/dsa-topological-sorting.md
New Post about "Grafos: Ordenação Topológica"
=> feat: Added new Post "Grafos: Ordenação Topológica"

.github/dependabot.yml
=> chore: remove assignees from dependabot configuration

_content/events/book-realtime-gaming-leaderboard.md, _content/events/book-storage-system-design.md, _content/events/dsa-mst.md
=> events: Adjusting next events calendar

_content/events/book-realtime-gaming-leaderboard.md, _content/events/book-storage-system-design.md, _content/events/dsa-mst.md
=> Fixing next events dates

_content/posts/2025-04-07-system-design-object-storage-like-s3.md, package-lock.json, package.json, src/app/globals.css, src/lib/posts.ts
Adding the new article
Also adding the rehype-slug, so we get links/anchos for the page titles and we can work with indexes.
=> articles: Add new article on designing an object storage system similar to S3

.github/c3.github-issues
To use this file you need to have installed the VSCode extensions installed https://marketplace.visualstudio.com/items/?itemName=ms-vscode.vscode-github-issue-notebooks
=> feat: Add GitHub issues notebook

_content/events/book-storage-system-design.md
=> fix: Update registration link for the book storage system design event

_content/posts/2025-04-11-livros-sobre-domain-driven-design.md
=> feat: Add a new post on essential books about Domain-Driven Design (DDD)

_content/events/2024-07-22-google-map-part1.md
=> feat: Added SD google map event

_content/events/2024-06-17-google-map-part1.md, _content/events/2024-06-17-proximity-service-part.md, package-lock.json
=> feat: Added event Clube do Livro: Proximity Service — Parte 2

_content/events/book-distributed-email-system.md
=> fix: update recording link for the Book Distributed Email System event

_content/_examples/event-example.md, _content/events/live-tips-vscode-copilot-agent-mode.md
=> feat(events): add live tips event for VSCode, Copilot, and Agent Mode

_content/events/2025-05-12-book-realtime-gaming-leaderboard.md, _content/events/2025-05-26-book-payment-system.md, _content/events/2025-06-09-digital-wallet.md
Adjusting SD schedule
- [x I tested the features already implemented.
=> schedule: Adjust date postponing SD chapters

_content/events/2025-05-18-dsa-backtracking.md, _content/events/2025-05-19-dsa-backtracking.md, _content/events/live-tips-vscode-copilot-agent-mode.md
=> schedule: adjusts

_content/posts/dsa-graph-tips.md
=> fix(graph): update graph representation to use undirected edges

_content/events/2024-06-17-google-map-part1.md, _content/events/2024-06-17-proximity-service-part.md, _content/events/2024-07-22-google-map-part1.md, _content/events/2024-07-29-google-map-part2.md, _content/events/2025-05-26-book-payment-system.md, _content/events/2025-06-09-digital-wallet.md, _content/posts/2025-04-07-system-design-object-storage-like-s3.md
=> fix(titles): replace em dash with hyphen in event titles for consistency

.vscode/extensions.json
=> chore: add initial VS Code extensions recommendations

_content/events/book-sd-rate-limiter-part1.md, _content/events/book-sd-rate-limiter-part2.md
Add event details for Clube do Livro sessions on rate limiters
=> feat(events): add event details for Clube do Livro sessions on rate limiters

_content/events/book-sd-back-of-the-envelope-estimation-part1.md, _content/events/book-sd-back-of-the-envelope-estimation-part2.md, _content/events/book-sd-back-of-the-envelope-estimation-part3.md
Add book club sessions for scaling systems series
=> feat(events): add book club sessions for scaling systems series

_content/events/book-sd-back-of-the-envelope-estimation.md
Add "Clube do Livro: Back-of-the-envelope Estimation" event details
=> feat(event): add "Clube do Livro: Back-of-the-envelope Estimation" event details

_content/events/book-sd-framework-system-design-interviews-part1.md, _content/events/book-sd-framework-system-design-interviews-part2.md
Add System Design Interviews book club sessions
=> feat(events): add System Design Interviews book club sessions

_content/events/book-sd-consistent-hashing.md
add new event for Clube do Livro on Consistent Hashing
=> feat(event): add new event for Clube do Livro on Consistent Hashing

_content/events/book-sd-key-value-store.md
Add key-value store event details
=> feat(event): Add key-value store event details

_content/events/book-sd-unique-id-generator-in-distributed-systems.md
add unique ID generator event details
=> feat(event): add unique ID generator event details

_content/events/book-sd-url-shortener.md
Add book club event for URL shortener
=> feat(event): add book club event for URL shortener

_content/events/book-sd-web-crawler.md
add new event for "Clube do Livro: Web Crawler"
=> feat(event): add new event for "Clube do Livro: Web Crawler"

_content/events/book-sd-notification-system.md
Add book club notification system event details
=> feat(events): add book club notification system event details

_content/events/book-sd-news-feed-system-part1.md, _content/events/book-sd-news-feed-system-part2.md
Add initial content for "Clube do Livro: Sistema de News Feed" parts 1 and 2
=> feat(events): add initial content for "Clube do Livro: Sistema de News Feed" parts 1 and 2

_content/events/book-sd-chat-system.md
Add book club chat system event details
=> feat(event): add book club chat system event details

_content/events/book-sd-search-autocomplete-system.md
Add book club event details for autocomplete system design
=> feat(event): add book club event details for autocomplete system design

_content/events/book-sd-design-youtube.md
add new event "Clube do Livro: Design YouTube"
=> feat(event): add new event "Clube do Livro: Design YouTube"

_content/events/book-sd-nearby-friends.md
add event details for "Clube do Livro: Amigos por Perto"
=> feat(events): add event details for "Clube do Livro: Amigos por Perto"

_content/events/book-sd-distributed-message-queue.md
add Clube do Livro event details for Distributed Message Queue
=> feat(event): add Clube do Livro event details for Distributed Message Queue

_content/events/book-sd-metrics-monitoring-alerting-system.md
This pull request adds a new event to the `_content/events` directory. The event details focus on designing a scalable metrics monitoring and alerting system.
Event addition:
* [`_content/events/book-sd-metrics-monitoring-alerting-system.md`](diffhunk://#diff-8a3821578d0efbdcc3bae882726a6c79070c57252300ed83f9153d6d5273c86dR1-R9): Introduced a new event titled "Clube do Livro: Sistema de Monitorização de Métricas e Alertas," including details such as description, date, time, location, and a link to the event recording.
=> feat(event): add book club event details for metrics monitoring and alerting system

_content/events/book-sd-digital-wallet.md, _content/events/book-sd-payment-system.md, _content/events/book-sd-realtime-gaming-leaderboard.md, _content/events/dsa-backtracking.md
Pushing all events one week ahead
=> fix: update event dates for "Clube do Livro" series

src/assets/inline-code.css, src/lib/posts.ts, tailwind.config.ts
- Added inline code styling in a new CSS file for better readability.
- Updated post processing to allow HTML and preserve inline code formatting. close #115
**Before**
**After**
#115
=> fix: enhance inline code styling and processing

_content/events/book-sd-storage-system-design.md, docs/examples/event-example.md
=> fix: update postLink for event examples to reflect new URL

imageLoader.ts, next.config.ts, src/app/posts/[id]/page.tsx, src/components/AuthorAvatar.tsx
- Introduced AuthorAvatar component to render author images or initials.
- Integrated AuthorAvatar in the Post component to enhance author display.
- Added functionality to extract GitHub usernames for avatar images.
**Before**
**After**
close #321
=> feat: add AuthorAvatar component for displaying author avatars

.github/ISSUE_TEMPLATE/feature-request.yml
=> refactor(issue-template): change 'Use Case' field to not be required

src/app/codigo-conduta/page.tsx, src/app/layout.tsx
feat(codigo-conduta): add código de conduta page with guidelines for community
https://github.com/craft-code-club/blog-c3/issues/108
=> feat(codigo-conduta): add código de conduta page with guidelines for community #close #108

_content/events/dsa-skip-list.md
=> docs(dsa-skip-list): add post link to skip list event details

src/app/layout.tsx
=> refactor: remove unused pages

_content/posts/dsa-bellman-ford.md, _content/posts/dsa-dijkstra.md, _content/posts/dsa-graph-tips.md, _content/posts/livros-sobre-domain-driven-design.md, _content/posts/sd-object-storage-like-s3.md
=> fix(authors): update Wilson Gomes' GitHub link to correct username

src/components/EventCard.tsx
=> feat(EventCard): wrap event title in a link for better navigation
